export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'


//Fetch COVID NEWS

export const FETCH_DATA_COVID = 'FETCH_DATA_COVID'

// * Restaurants Action
export const FETCH_RESTAURANT_PENDING = 'FETCH_RESTAURANT_PENDING'
export const FETCH_RESTAURANT_REJECTED = 'FETCH_RESTAURANT_REJECTED'
export const FETCH_RESTAURANT_FULFILLED = 'FETCH_RESTAURANT_FULFILLED'

export const FETCH_ONE_RESTAURANT_FULFILLED = 'FETCH_ONE_RESTAURANT_FULFILLED'

export const CREATE_RESTAURANT_PENDING = 'FETCH_RESTAURANT_PENDING'
export const CREATE_RESTAURANT_REJECTED = 'FETCH_RESTAURANT_REJECTED'
export const CREATE_RESTAURANT_FULFILLED = 'FETCH_RESTAURANT_FULFILLED'

// * Hospitals Action
export const FETCH_HOSPITAL_PENDING = 'FETCH_HOSPITAL_PENDING'
export const FETCH_HOSPITAL_REJECTED = 'FETCH_HOSPITAL_REJECTED'
export const FETCH_HOSPITAL_FULFILLED = 'FETCH_HOSPITAL_FULFILLED'

export const FETCH_ONE_HOSPITAL_FULFILLED = 'FETCH_ONE_HOSPITAL_FULFILLED'

export const CREATE_HOSPITAL_PENDING = 'FETCH_HOSPITAL_PENDING'
export const CREATE_HOSPITAL_REJECTED = 'FETCH_HOSPITAL_REJECTED'
export const CREATE_HOSPITAL_FULFILLED = 'FETCH_HOSPITAL_FULFILLED'