export {default as HomePage} from './HomePage'
export {default as HistoryPage} from './HistoryPage'
export {default as LoginPage} from './LoginPage'
export {default as RegisterPage} from './RegisterPage'
export {default as TestPage} from './TestPage'
export {default as VerifyPage} from './VerifyPage'